# Generated by Django 6.0.4 on 2026-04-15 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rupayapp', '0003_remove_transaction_operator_transaction_action_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Use exatamente 8 dígitos (ex.: 12345678).', regex='^\\d{8}$')]),
        ),
    ]
