# Generated by Django 6.0.4 on 2026-04-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rupayapp', '0004_alter_user_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
