# Generated by Django 6.0.4 on 2026-04-22 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rupayapp', '0005_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Use exatamente 10 dígitos (ex.: 1234567890).', regex='^\\d{10}$')]),
        ),
    ]
