# Generated by Django 6.0.4 on 2026-05-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rupayapp', '0006_alter_card_number_10digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Claro'), ('dark', 'Escuro'), ('high_contrast', 'Alto Contraste')], default='light', max_length=15),
        ),
    ]
