# Generated by Django 6.0.4 on 2026-05-02 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rupayapp', '0008_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='rupayapp.user'),
        ),
    ]
